# This is a basic workflow to help you get started with Actions

name: CI/CD Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Uruchom testy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repozytorium
        uses: actions/checkout@v3
      - name: Set Python 3.10
        uses: actions/setup-python@v4
        with: 
          python-version: 3.10
      - name: Install dependencies
        run: |
          pip install flask
          pip install requests
          pip install pytest
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q
  # This workflow contains a single job called "build"
  build:
    name: DockerImage building
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: test
    steps: 
      - name: Chceckout repository
        uses: actions/checkout@v3
      - name: Docker Image build
        run: |
          docker build -t weather-forecast .

